In [ ]:
!pip install tensorflow

In [ ]:
!pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113


In [4]:
import torch

In [ ]:
a = torch.FloatTensor([1, 2])
print(a)
print(a.shape)

tensor([1., 2.])
torch.Size([2])


In [ ]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
print(b)
print(b.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [ ]:
x = torch.FloatTensor(2,3,4)
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

In [ ]:
x = torch.IntTensor(3, 2, 4)
print(x)
x = torch.IntTensor(3, 2, 4).zero_()
print(x)

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]]], dtype=torch.int32)
tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]]], dtype=torch.int32)


In [ ]:
b.view(3, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [ ]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
b.view(-1)

tensor([1., 2., 3., 4., 5., 6.])

In [ ]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [ ]:
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [ ]:
a.type_as(torch.ByteTensor())

tensor([  1,   3, 249], dtype=torch.uint8)

In [ ]:
a

tensor([ 1.5000,  3.2000, -7.0000])

In [ ]:
a = torch.FloatTensor([[10, 2, 5], [5, 13, 54], [2, 0, 6]])
a

tensor([[10.,  2.,  5.],
        [ 5., 13., 54.],
        [ 2.,  0.,  6.]])

In [ ]:
a[0:2, 0:2]

tensor([[10.,  2.],
        [ 5., 13.]])

In [ ]:
a = torch.FloatTensor([[1, 2, 3], [90, 80, 70], [400, 50, 64]])
b = torch.FloatTensor([[-1, -2, -3], [-1, -2, -60], [10, -20, 3]])

In [ ]:
a + b

tensor([[  0.,   0.,   0.],
        [ 89.,  78.,  10.],
        [410.,  30.,  67.]])

In [ ]:
a.add(b)

tensor([[  0.,   0.,   0.],
        [ 89.,  78.,  10.],
        [410.,  30.,  67.]])

In [ ]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -90.,  -80.,  -70.],
        [-400.,  -50.,  -64.]])

In [ ]:
a - b

tensor([[  2.,   4.,   6.],
        [180., 160., 140.],
        [800., 100., 128.]])

In [ ]:
a.sub(b)

tensor([[  2.,   4.,   6.],
        [180., 160., 140.],
        [800., 100., 128.]])

In [ ]:
a * b

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-8.1000e+03, -6.4000e+03, -4.9000e+03],
        [-1.6000e+05, -2.5000e+03, -4.0960e+03]])

In [ ]:
a.mul(b)

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-8.1000e+03, -6.4000e+03, -4.9000e+03],
        [-1.6000e+05, -2.5000e+03, -4.0960e+03]])

In [ ]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.]])

In [ ]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.]])

In [ ]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [ ]:
a != b

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
a < b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [ ]:
a > b

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
a[a > b]

tensor([  1.,   2.,   3.,  90.,  80.,  70., 400.,  50.,  64.])

In [ ]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [ 0.8940, -0.9939,  0.7739],
        [-0.8509, -0.2624,  0.9200]])

In [ ]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [       inf, 5.5406e+34, 2.5154e+30],
        [       inf, 5.1847e+21, 6.2351e+27]])

In [ ]:
a.mean()

tensor(84.4444)

In [ ]:
a.max(0)

torch.return_types.max(
values=tensor([400.,  80.,  70.]),
indices=tensor([2, 1, 1]))

In [ ]:
a.t()

tensor([[  1.,  90., 400.],
        [  2.,  80.,  50.],
        [  3.,  70.,  64.]])

In [ ]:
a = torch.FloatTensor([1, 2, 3, 4, 8, 61])
b = torch.FloatTensor([-1, -22, -4, -6, -85, -10])

In [ ]:
a.dot(b)

tensor(-1371.)

In [ ]:
a @ b

tensor(-1371.)

In [ ]:
a = torch.FloatTensor([[1, 2, 3], [90, 80, 70], [400, 50, 64]])
b = torch.FloatTensor([[-1, -2, -3], [-1, -2, -60], [10, -20, 3]])

In [ ]:
a.mm(b)

tensor([[   27.,   -66.,  -114.],
        [  530., -1740., -4860.],
        [  190., -2180., -4008.]])

In [ ]:
a @ b

tensor([[   27.,   -66.,  -114.],
        [  530., -1740., -4860.],
        [  190., -2180., -4008.]])

In [ ]:
print(a.shape, b.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [3]:
import numpy as np

a = np.random.rand(3, 3)
a

array([[0.29351994, 0.62870479, 0.031392  ],
       [0.09454906, 0.77301406, 0.78800806],
       [0.53059679, 0.68140923, 0.31623194]])

In [ ]:
b = torch.from_numpy(a)
b

tensor([[0.2468, 0.8458, 0.8742],
        [0.9518, 0.0536, 0.8063],
        [0.4110, 0.0933, 0.9177]], dtype=torch.float64)

In [ ]:
b -= b
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [ ]:
a = torch.FloatTensor(2, 3, 4)
x = a.numpy()
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
def forward_pass(X, w):
    return torch.sigmoid(X @ w)

X = torch.FloatTensor([[-5, 5], [2, 3], [1, -1]])
w = torch.FloatTensor([[-0.5], [2.5]])
result = forward_pass(X, w)
print('result: {}'.format(result))

result: tensor([[1.0000],
        [0.9985],
        [0.0474]])


In [5]:
torch.cuda.is_available()

True

In [6]:
torch.zeros(1).cuda()

tensor([0.], device='cuda:0')

In [7]:
x = torch.FloatTensor(1024, 1024).uniform_()
x

tensor([[0.0556, 0.3632, 0.5479,  ..., 0.2267, 0.7168, 0.6343],
        [0.3974, 0.9921, 0.7282,  ..., 0.7678, 0.8557, 0.3698],
        [0.1073, 0.3701, 0.9450,  ..., 0.5871, 0.3570, 0.0319],
        ...,
        [0.3261, 0.5069, 0.5972,  ..., 0.8232, 0.4699, 0.0738],
        [0.3334, 0.6289, 0.3252,  ..., 0.5798, 0.5800, 0.8847],
        [0.4062, 0.3683, 0.4835,  ..., 0.8658, 0.0502, 0.1143]])

In [8]:
x = x.cuda()
x.is_cuda

True

In [9]:
x

tensor([[0.0556, 0.3632, 0.5479,  ..., 0.2267, 0.7168, 0.6343],
        [0.3974, 0.9921, 0.7282,  ..., 0.7678, 0.8557, 0.3698],
        [0.1073, 0.3701, 0.9450,  ..., 0.5871, 0.3570, 0.0319],
        ...,
        [0.3261, 0.5069, 0.5972,  ..., 0.8232, 0.4699, 0.0738],
        [0.3334, 0.6289, 0.3252,  ..., 0.5798, 0.5800, 0.8847],
        [0.4062, 0.3683, 0.4835,  ..., 0.8658, 0.0502, 0.1143]],
       device='cuda:0')

In [10]:
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.cuda().mul(b.cuda()).cpu()

In [11]:
c

tensor([[0.2101, 0.7783, 0.0119,  ..., 0.2345, 0.4446, 0.3548],
        [0.5575, 0.0379, 0.1153,  ..., 0.5127, 0.0144, 0.0726],
        [0.4991, 0.4492, 0.0663,  ..., 0.0275, 0.2469, 0.4349],
        ...,
        [0.2447, 0.7496, 0.0983,  ..., 0.4098, 0.8258, 0.1924],
        [0.5483, 0.1743, 0.2153,  ..., 0.2263, 0.0266, 0.2630],
        [0.0858, 0.1262, 0.8274,  ..., 0.0745, 0.1080, 0.5509]])

In [12]:
a

tensor([[0.4470, 0.9106, 0.0318,  ..., 0.3073, 0.5435, 0.7625],
        [0.6672, 0.0461, 0.1814,  ..., 0.9921, 0.0993, 0.3906],
        [0.5613, 0.8714, 0.2699,  ..., 0.9963, 0.5024, 0.6323],
        ...,
        [0.2742, 0.7913, 0.1289,  ..., 0.9805, 0.9051, 0.2221],
        [0.6752, 0.8175, 0.4985,  ..., 0.5320, 0.0400, 0.4401],
        [0.3567, 0.3419, 0.8576,  ..., 0.2308, 0.2162, 0.7999]])

In [13]:
a = torch.FloatTensor(10000, 10000).uniform_().cpu()
b = torch.FloatTensor(10000, 10000).uniform_().cuda()

In [14]:
a + b

RuntimeError: ignored

In [15]:
x = torch.FloatTensor(5, 5, 5).uniform_()

if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[[1.3552, 1.8215, 1.7672, 1.2356, 1.1383],
         [1.3993, 1.6360, 1.8957, 1.5835, 1.6944],
         [1.3540, 1.8847, 1.3984, 1.6148, 1.5952],
         [1.2629, 1.2318, 1.5038, 1.8880, 1.1291],
         [1.1284, 1.4111, 1.0570, 1.3003, 1.4138]],

        [[1.9621, 1.4772, 1.2717, 1.0672, 1.4829],
         [1.9975, 1.1181, 1.2531, 1.1154, 1.0030],
         [1.4026, 1.2004, 1.5743, 1.6221, 1.1254],
         [1.8483, 1.0030, 1.4354, 1.9777, 1.5847],
         [1.4686, 1.4975, 1.7330, 1.3408, 1.5936]],

        [[1.9956, 1.9421, 1.5243, 1.2891, 1.6570],
         [1.5510, 1.0597, 1.7464, 1.0766, 1.6889],
         [1.1834, 1.4618, 1.9692, 1.4843, 1.4072],
         [1.0687, 1.8049, 1.7945, 1.0943, 1.5807],
         [1.9025, 1.3959, 1.2021, 1.7590, 1.0765]],

        [[1.9849, 1.7507, 1.2985, 1.3103, 1.5122],
         [1.4739, 1.7433, 1.8085, 1.4678, 1.1713],
         [1.0194, 1.9726, 1.9153, 1.2831, 1.3075],
         [1.6898, 1.7593, 1.1941, 1.8411, 1.9823],
         [1.8683, 1.4186,

In [16]:
from torch.autograd import Variable

In [17]:
x = torch.FloatTensor(3, 1).uniform_()
y = torch.FloatTensor(3, 1).uniform_()
w = torch.FloatTensor(3, 3).uniform_() 
b = torch.FloatTensor(3, 1).uniform_()

x = Variable(x, requires_grad=True)
y = Variable(x, requires_grad=False)
w = Variable(w, requires_grad=True)
b = Variable(b, requires_grad=True)

y_pred = (w @ x).add_(b)

loss = (y_pred - y).sum()

loss.backward()

In [18]:
x.grad

tensor([[1.4785],
        [1.5792],
        [1.0346]])

In [19]:
x.data

tensor([[0.6744],
        [0.4903],
        [0.6466]])